site_name: happy-vllm documentation
repo_url: https://github.com/OSS-Pole-Emploi/happy_vllm
repo_name: OSS-Pole-Emploi/happy_vllm

# see https://squidfunk.github.io/mkdocs-material/setup/
theme:
  name: material
  logo: source/assets/logo/logo_happy_vllm.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
      accent: pink

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: pink
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

nav:
  - Home: 
    - Quickstart and installation: index.md
    - Arguments: arguments.md
    - Endpoints: endpoints/endpoints.md
    - Functionalities added by happy_vLLM: pros.md
    - Deploying with Docker: deploying_with_docker.md
    - Code Reference: reference/
  - Endpoints: 
    - Endpoints overview: endpoints/endpoints.md
    - Technical: endpoints/technical.md
    - Generate and generate_stream: endpoints/generate.md
    - Tokenizer : endpoints/tokenizer.md
    - Data manipulation: endpoints/data_manipulation.md
    


plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences






