name: Build & Tests
on:
  push:
    paths:
      - 'src/**'
      - '!*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
      - 'release/v*'
    paths:
      - 'src/**'
      - '!*.md'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    - name: Install the project and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .[test]
        pytest
        python -m mypy --ignore-missing-imports --allow-redefinition --no-strict-optional -p src
