name: Wheel setup
on:
  push:
    branches:
      - 'main'
      - 'release/v*'
    paths:
      - 'src/**'
      - '!*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
      - 'release/v*'
    paths:
      - 'src/**'
      - '!*.md'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install flake8
          python -m build
      - name: Install library and test it
        run: |
          cd dist
          whl_files=( *.whl )
          whl_file=${whl_files[0]}
          pip install $whl_file
          python -c "from happy_vllm import utils; print(utils.get_package_version())"